### PR TITLE
#31 #32 Enable file sourcing from project root

### PR DESCRIPTION
**Pull request by sm-Fifteen**
I know this kind of thing is generally better suited for a config file (and it would probably be a good idea to move it there), but for now it seems to do the trick.

----

Edit by @Arcanemagus to link to the issues
Related to #31, #32.

### CODE REVIEW

**Comment by SpainTrain** [comment]
So given that this materially affects what passes lint or not, it should probably be a config option (even if on by default).  It is pretty easy:

```coffeescript
 config:
    externalSources:
      type: 'boolean'
      title: 'External sources (-x)'
      description: 'Allow "source" outside of target file (file being linted).'
      default: false  # or true
```

```coffeescript
@subscriptions.add atom.config.observe 'linter-shellcheck.externalSources',
      (externSources) =>
        @externSources = externSources
```

```coffeescript
parameters = [ '-f', 'gcc', '-' ]
parameters.unshift('-x') if @externSources
```

**Comment by Riboshom** [comment]
You're probably going to need to add a field to set the working directory as well, otherwise dynamic sourcing (like `source "$(xdg-user-dir DESKTOP)/script-source.sh"` which normaly requires directives with static paths for shellcheck to resolve) won't work as shellcheck depends on the current working directory to resolve those.

**Comment by Arcanemagus** [comment]
@Riboshom this is your PR, so go for it :stuck_out_tongue:

Also a tip for future PR's: Work on a separate branch, that way you can update branches like `master` without affecting your work, and if it eventually doesn't get merged you can simply delete the branch without having to do some tricks to get it back to a "good" state.

**Comment by Riboshom** [comment]
@Arcanemagus Oh, right! Look at me, forgetting how to PR again.

I haven't tinkered much wth the atom plugin API yet (this was just a quick and dirty hack to get things to work on my machine), but I'll look into it when I get time.

**Comment by Arcanemagus** [comment]
Closing this as it needs to be re-written, and is partially superseded by #34 anyway.

I've asked in #31 whether setting the working directory to the project root instead of the file's directory is what is desired in the first place as well.

**Pull request closed without merging**
